### ISSUE TITLE
Check if you have an absolute path before looking for a file

### ISSUE THREAD

**Issue by jypeter** [kelvinou01/conda-which#2]
If you want to make your extension more foolproof, you could **check if the path supplied by the user is absolute** before looking for the file

On the other hand, you could also:
- try to find a file even if the path is relative, but you may want to display only a few hits if you get lots of results
- prepend the environments' paths, if the supplied relative path starts with `lib`, `share`, `bin`, ...

```
(bauer_env)  >conda which lib/python3.12/site-packages/bs4/formatter.py
Environments from ~/.condarc/environments.txt: {'/home/share/unix_files/cdat/miniconda3_21-02/envs/cdatm_py3', '/home/share/unix_files/cdat/miniconda3_2024-03/envs/bauer_env', '/home/share/unix_files/cdat/miniconda3_2024-03'}

File 'lib/python3.12/site-packages/bs4/formatter.py' does not exist

(bauer_env) >conda which /home/share/unix_files/cdat/miniconda3_2024-03/envs/bauer_env/lib/python3.12/site-packages/bs4/formatter.py
Environments from ~/.condarc/environments.txt: {'/home/share/unix_files/cdat/miniconda3_2024-03/envs/bauer_env', '/home/share/unix_files/cdat/miniconda3_2024-03', '/home/share/unix_files/cdat/miniconda3_21-02/envs/cdatm_py3'}
File '/home/share/unix_files/cdat/miniconda3_2024-03/envs/bauer_env/lib/python3.12/site-packages/bs4/formatter.py' belongs to
  📦 Package: beautifulsoup4-4.12.3-pyha770c72_0
  🌏 Environment: /home/share/unix_files/cdat/miniconda3_2024-03/envs/bauer_env
```

**Comment by kelvinou01** [comment]
Hey @jypeter, the behavior with relative paths is intended. In linux convention, relative paths are assumed to be w.r.t the cwd. 

Also, prepending the environments' paths would lead to correctness issues. For example, `bin/clean` may be used by two different packages installed in two different environments.

**Comment by kelvinou01** [comment]
Hey @jypeter, the behavior with relative paths is intended. In linux convention, relative paths are assumed to be w.r.t the cwd.

Also, prepending the environments' paths would lead to correctness issues. For example, bin/clean may be used by two different packages installed in two different environments.
